<?php

declare(strict_types=1);

// This file is auto-generated by bin/ide.php. Do not edit it manually.

namespace Filament\Actions {
    /**
     * @method static inlineConfirmation(int $timeout = 3000, \Closure|bool|null $closeDropdown = NULL)
     * @method bool isInlineConfirmationEligible()
     * @method static holdToConfirm(int $duration = 1500, \Closure|bool|null $closeDropdown = NULL)
     * @method bool isHoldToConfirmEligible()
     */
    class Action {}
}

namespace Filament\Tables\Actions {
    /**
     * @method static inlineConfirmation(int $timeout = 3000, \Closure|bool|null $closeDropdown = NULL)
     * @method bool isInlineConfirmationEligible()
     * @method static holdToConfirm(int $duration = 1500, \Closure|bool|null $closeDropdown = NULL)
     * @method bool isHoldToConfirmEligible()
     */
    class Action {}
}

namespace Filament\Infolists\Components\Actions {
    /**
     * @method static inlineConfirmation(int $timeout = 3000, \Closure|bool|null $closeDropdown = NULL)
     * @method bool isInlineConfirmationEligible()
     * @method static holdToConfirm(int $duration = 1500, \Closure|bool|null $closeDropdown = NULL)
     * @method bool isHoldToConfirmEligible()
     */
    class Action {}
}
