<?php

declare(strict_types=1);

// This file is auto-generated by bin/ide.php. Do not edit it manually.

namespace Filament\Actions {
    /**
     * @method static inlineConfirmation(int $timeout = 3000)
     * @method bool isInlineConfirmationEligible()
     */
    class Action {}
}

namespace Filament\Tables\Actions {
    /**
     * @method static inlineConfirmation(int $timeout = 3000)
     * @method bool isInlineConfirmationEligible()
     */
    class Action {}
}

namespace Filament\Infolists\Components\Actions {
    /**
     * @method static inlineConfirmation(int $timeout = 3000)
     * @method bool isInlineConfirmationEligible()
     */
    class Action {}
}
